# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'loadFileDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for loadFileDemo
  pod 'SSZipArchive'
  pod 'PPNetworkHelper',:git => 'https://github.com/jkpang/PPNetworkHelper.git'
  pod 'YYCache'
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'SDWebImage' 
end
